-- Server-backed favourites behind the heart buttons.
-- see: docs/decisions/favourites.md

CREATE TABLE favourites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tmdb_id bigint NOT NULL,
    media_type text NOT NULL CHECK (media_type IN ('movie', 'tv')),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_favourites_user_title UNIQUE (user_id, tmdb_id, media_type)
);

CREATE INDEX idx_favourites_user ON favourites (user_id);

-- Rule 5: every user-scoped table bumps the owner's activity clock.
-- see: docs/decisions/migrations.md
CREATE TRIGGER trg_favourites_touch
    AFTER INSERT OR UPDATE OR DELETE ON favourites
    FOR EACH ROW EXECUTE FUNCTION touch_user_last_activity();
