-- Per-user playback position for resume.
-- see: docs/decisions/watch-progress.md

CREATE TABLE watch_progress (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tmdb_id bigint NOT NULL,
    media_type text NOT NULL CHECK (media_type IN ('movie', 'tv')),
    season_number int,
    episode_number int,
    progress_seconds int NOT NULL,
    duration_seconds int,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (media_type = 'tv' OR (season_number IS NULL AND episode_number IS NULL))
);

-- Two partial unique indexes, one per row shape. A single unique index over the
-- nullable columns cannot stop duplicate movie rows: Postgres treats (NULL, NULL)
-- as distinct from itself under its default NULLS DISTINCT.
CREATE UNIQUE INDEX uq_watch_progress_movie
    ON watch_progress (user_id, tmdb_id) WHERE season_number IS NULL;
CREATE UNIQUE INDEX uq_watch_progress_tv
    ON watch_progress (user_id, tmdb_id, season_number, episode_number) WHERE season_number IS NOT NULL;

CREATE INDEX idx_watch_progress_user_updated ON watch_progress (user_id, updated_at DESC);

-- Rule 5: every user-scoped table bumps the owner's activity clock.
-- see: docs/decisions/migrations.md
CREATE TRIGGER trg_watch_progress_touch
    AFTER INSERT OR UPDATE OR DELETE ON watch_progress
    FOR EACH ROW EXECUTE FUNCTION touch_user_last_activity();
